/**
 *
 * $Id$
 */
package cleaningrobots.validation;

import cleaningrobots.State;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link cleaningrobots.Field}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FieldValidator {
	boolean validate();

	boolean validateXpos(int value);
	boolean validateYpos(int value);
	boolean validateStates(EList<State> value);

	boolean validateState(EList<State> value);
}
